name = "CS1660 Final..."
description = "Simple page with name and a countdown to your website's release date & time"

license = "GNU GPLv3"
licenselink = "https://github.com/mansoorbarri/coming-soon/blob/main/LICENCE"

homepage = "https://github.com/BrGram/cs1660-static-website"
demosite = "https://cshugo.mansoorbarri.com/"

tags = ["minimal", "dark", "personal", "countdown"]

authors = [
  {name = "Brian Grammer", homepage = "https://google.com"},
]

min_version = "0.111.3"
