name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify


      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/673075819708/locations/global/workloadIdentityPools/cs1660-pool-id/providers/github'
          service_account: 'github-action@cs1660-final-408012.iam.gserviceaccount.com' # UPDATE THIS TO YOUR SERVICE ACCOUNT

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public' # UPDATE THIS TO YOUR BUILD/FILES DIRECTORY
          destination: 'cs1660-final-bg' # UPDATE THIS TO YOUR BUCKET NAME
          parent: false
